CREATE TABLE MAIN_VIDEO (

    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    LINK VARCHAR(255) NOT NULL,
    PICTURE VARCHAR(255) NOT NULL,

) AUTO_INCREMENT = 1;

CREATE TABLE RELATED_VIDEO (

    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    LINK VARCHAR(255) NOT NULL,
    PICTURE VARCHAR(255) NOT NULL,
    MAIN_VIDEO_ID VARCHAR(255) NOT NULL,

) AUTO_INCREMENT = 1;